### ISSUE TITLE
[BUG][Kumano][Xperia 5 J9210][SailfishOS-4.4.0.72]: Vibration on Xperia 5 has the same short period in all cases.

### ISSUE THREAD

**Issue by VZuyev** [SailfishOS-SonyXperia/bugs#83] opened 2023-08-26 10:27 UTC
### Environment

```markdown
- **Platform: Kumano
- **Device: Xperia 5 J9210
- **Sailfish OS Version: 4.4.0.72+git1
- **Kernel version: 4.14
- **Droid-Hal Version: 10
- **Droid-System Version: 10
- **Software binaries version: SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_kumano
```

### Previously working on

```markdown
No
```

### Description

Vibration on my Xperia 5 when using Sailfish OS has the same short period in all cases. Vibration duration is not adjustable.

### Symptoms

Vibration has short period. Vibration duration is not adjustable.

### How to reproduce the bug

1. Application Componentgallery
2. Haptics
3. Long, Button, Keypad, Periodic has the same short period; Effect duration does not affect

1. CSD Tool
2. Individual tests
3. Vibrator - Vibration has short period

**Comment by Thaodan** [comment] 2023-08-26 17:57
Duplicate of #74.

**Comment by Thaodan** [comment] 2023-08-26 17:57
Duplicate of #74.

**Comment by Thaodan** [comment] 2023-08-26 17:57
Duplicate of #74.

**Closed as not planned by Thaodan** 2023-08-26 17:57 UTC
Labels: BUG, TRIAGE
