### ISSUE TITLE
[BUG][Kumano][Xperia 5 J9210][SailfishOS-4.4.0.68]: Favorite contacts in the Contacts application are arranged in two columns

### ISSUE THREAD

**Issue by VZuyev** [SailfishOS-SonyXperia/bugs#53] opened 2022-10-29 07:35 UTC
### Environment

```markdown
- **Platform: Kumano
- **Device: Xperia 5 J9210
- **Sailfish OS Version: 4.4.0.68
- **Kernel version: 4.14
- **Droid-Hal Version: 10
- **Droid-System Version: 10
- **Software binaries version: SW_binaries_for_Xperia_Android_10.0.7.1_r1_v12a_kumano
```

### Previously working on

```markdown
Sailfish_OS-Sailfish-SonyXperia-4.4.0.68-j9210-1.0.0.6
```

### Description

Favorite contacts in the Contacts application are arranged in two columns (in Xperia 10II they are arranged in three columns).

### Symptoms

Favorite contacts in the Contacts application are arranged in two columns (in Xperia 10II they are arranged in three columns).

### How to reproduce the bug

1. Contacts app
2. Add multiple contacts to favorites
3.

**Comment by VZuyev** [comment] 2022-10-29 21:10
![screen](https://user-images.githubusercontent.com/48154777/198852432-a4d2b152-c58a-4d73-beba-59768412675d.jpg)

**Comment by Thaodan** [comment] 2022-10-29 23:24
Can you try English? It could be because of the Cyrillic letter.
I just tried it with english, I could fit 3 contacts per row.

**Comment by VZuyev** [comment] 2022-10-30 10:22
I just tried it with english, I fit 2 contacts per row.

**Comment by Thaodan** [comment] 2022-10-30 11:20
Which font size setting?

**Comment by VZuyev** [comment] 2022-10-30 11:31
Normal

**Comment by voidanix** [comment] 2022-10-31 11:41
@Thaodan I assume you tested this on the Xperia 1, correct?

I also have 2 contacts per row on my 5 but never considered this an issue: this is because both seine and lena have a smaller `pixel_ratio 1.75` compared to bahamut's `pixel_ratio 2.0`, although they also have *slightly* physically smaller displays.

TBH setting `pixel_ratio 1.75` on my bahamut makes the UI font pretty hard to read, so I am not vouching for it to be changed **at all**, but if this really pisses you off you can do the following:

1. Comment the line `/desktop/sailfish/silica/theme_pixel_ratio` in `/etc/dbconf/db/vendor.d/locks/silica-configs.txt`
2. `devel-su dconf update`
3. `devel-su dconf write /desktop/sailfish/silica/theme_pixel_ratio 1.75`
4. `systemctl restart --user lipstick`

**Comment by Thaodan** [comment] 2022-10-31 11:43
I tested this on Xperia 5, I have both.

**Comment by VZuyev** [comment] 2022-10-31 21:31
> * Прокомментируйте строку `/desktop/sailfish/silica/theme_pixel_ratio`в `/etc/dbconf/db/vendor.d/locks/silica-configs.txt`
> 
> * `devel-su dconf update`
> 
> * `devel-su dconf write /desktop/sailfish/silica/theme_pixel_ratio 1.75`
> 
> * `systemctl restart --user lipstick`

Thank you

**Comment by Thaodan** [comment] 2022-11-23 19:52
Closing as working as intended. it is possible that the layout changes depending on your change.
For languages using latin fonts there are three rows for favorite contacts.

**Closed as completed by Thaodan** 2022-11-23 19:52 UTC
Labels: BUG, Worksforme
